version: '2'

services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - app
  app:
    image: node:8
    volumes:
      - ./app:/app
    working_dir: /app
    command: npm start
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:9.6
    volumes:
      - ./db:/var/lib/postgresql/data
    # environment:
    #   POSTGRES_PASSWORD: password
  